
import "@monorepo/ui/globals.css";

import type { Metadata } from "next";
import "./globals.css"
import { ThemeProvider } from "../providers/theme-provider";
import { use } from "react";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <>{children}</>
        {/* <ThemeProvider attribute="class" enableSystem> */}
        {/* {children} */}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
