
import "@monorepo/ui/globals.css";

import type { Metadata } from "next";
import "./globals.css"
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <ThemeProvider> */}
        {children}
        {/* </ThemeProvider> */}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}