"use client";
import type { UmkmCategory, UmkmCategoryOption, UmkmInterface, UmkmSubscriptionPlanInterface } from "@monorepo/types";
import { Button } from "@monorepo/ui/components/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@monorepo/ui/components/dialog";
import { Input } from "@monorepo/ui/components/input";import { Label } from "@monorepo/ui/components/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@monorepo/ui/components/select";import { Textarea } from "@monorepo/ui/components/textarea";
import { FileCheck2,Upload } from "lucide-react";import { useEffect,useState } from "react";import { toast } from "sonner";
const MAX=2*1024*1024;const allowed=new Set(["image/jpeg","image/png"]);
const readFile=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error("Gambar tidak dapat dibaca"));reader.readAsDataURL(file);});
export function UmkmFormDialog({open,item,categories,plans,loading,onOpenChange,onSubmit}:Readonly<{open:boolean;item?:UmkmInterface|null;categories:UmkmCategoryOption[];plans:UmkmSubscriptionPlanInterface[];loading?:boolean;onOpenChange:(open:boolean)=>void;onSubmit:(value:UmkmInterface)=>Promise<void>|void}>){
 const [form,setForm]=useState({name:"",category:"" as UmkmCategory|"",description:"",address:"",whatsapp:"",external_url:"",plan_id:""});const[file,setFile]=useState<File|null>(null);
 useEffect(()=>{if(!open)return;setForm({name:item?.name||"",category:item?.category||"",description:item?.description||"",address:item?.address||"",whatsapp:item?.whatsapp||"",external_url:item?.external_url||"",plan_id:item?.plan_id||""});setFile(null);},[item,open]);
 const choose=(next?:File)=>{if(!next){setFile(null);return;}if(!allowed.has(next.type)){toast.error("Gambar hanya boleh JPEG atau PNG");return;}if(next.size>MAX){toast.error("Ukuran gambar maksimal 2 MB");return;}setFile(next);};
 const submit=async()=>{if(!form.name.trim()||!form.category||!form.description.trim()||!form.address.trim()||!form.whatsapp.trim()||(!item&&(!file||!form.plan_id))){toast.error("Data wajib, gambar, dan paket subscription harus dilengkapi");return;}const imageData=file?await readFile(file):undefined;await onSubmit({id:item?.id,...form,plan_id:form.plan_id||undefined,category:form.category as UmkmCategory,image_data:imageData,image_original_name:file?.name,image_mime_type:file?.type,image_size:file?.size});};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{item?"Edit UMKM":"Tambah UMKM"}</DialogTitle><DialogDescription>Simpan sebagai draft, lalu ajukan untuk ditinjau pengurus.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2">
  <div className="space-y-2 sm:col-span-2"><Label>Nama Usaha</Label><Input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></div>
  <div className="space-y-2"><Label>Kategori</Label><Select value={form.category} onValueChange={value=>setForm(v=>({...v,category:value as UmkmCategory}))}><SelectTrigger><SelectValue placeholder="Pilih kategori"/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div>
  <div className="space-y-2"><Label>WhatsApp</Label><Input value={form.whatsapp} onChange={e=>setForm(v=>({...v,whatsapp:e.target.value}))} placeholder="62812..."/></div>
  {!item||item.subscription_status==="DRAFT"?<div className="space-y-2 sm:col-span-2"><Label>Paket Subscription</Label><Select value={form.plan_id} onValueChange={value=>setForm(v=>({...v,plan_id:value}))}><SelectTrigger><SelectValue placeholder="Pilih paket iklan"/></SelectTrigger><SelectContent>{plans.map(plan=><SelectItem key={plan.id} value={plan.id!}>{plan.name} - Rp {Number(plan.price||0).toLocaleString("id-ID")} / {plan.duration_days} hari</SelectItem>)}</SelectContent></Select></div>:null}
  <div className="space-y-2 sm:col-span-2"><Label>Deskripsi</Label><Textarea value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></div>
  <div className="space-y-2 sm:col-span-2"><Label>Alamat</Label><Textarea value={form.address} onChange={e=>setForm(v=>({...v,address:e.target.value}))}/></div>
  <div className="space-y-2 sm:col-span-2"><Label>Tautan Eksternal</Label><Input type="url" value={form.external_url} onChange={e=>setForm(v=>({...v,external_url:e.target.value}))} placeholder="https://... (opsional)"/></div>
  <div className="space-y-2 sm:col-span-2"><Label>Logo / Foto Utama</Label><label className="flex min-h-24 cursor-pointer items-center justify-center rounded-md border border-dashed border-slate-300 bg-slate-50 p-4"><input className="sr-only" type="file" accept="image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0])}/>{file?<span className="flex items-center gap-2 text-sm"><FileCheck2 className="h-5 w-5 text-emerald-600"/>{file.name}</span>:<span className="flex flex-col items-center gap-1 text-sm text-slate-500"><Upload className="h-5 w-5"/>{item?"Pilih gambar untuk mengganti":"JPEG/PNG maksimal 2 MB"}</span>}</label></div>
 </div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Batal</Button><Button disabled={loading} onClick={submit}>{loading?"Menyimpan...":"Simpan Draft"}</Button></DialogFooter></DialogContent></Dialog>;
}
